# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: PR Updater

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  test:
    name: Publish conclusion status
    runs-on: macos-13
    permissions:
      statuses: write 
    steps:
    - name: Publish conclusion status
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "${{ github.event.workflow_run.conclusion }}",
          "context": "Run iOS tests",
          "target_url": "${{ github.event.workflow_run.html_url }}"
          }' \
        --fail