# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_SCHEME: ReccoUITests
  DEVICE_NAME: iPhone 14
  DEVICE_OS: 16.4

jobs:
  test:
    name: Run iOS tests
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'
    - name: Test Print env vars 1
      run: 
        echo 1 $TEST_SCHEME $DEVICE_NAME $DEVICE_OS
    - name: Test Print env vars 2
      run: 
        echo "2 $TEST_SCHEME $DEVICE_NAME $DEVICE_OS"
    - name: Test Print env vars 3
      run: 
        echo '2 $TEST_SCHEME $DEVICE_NAME $DEVICE_OS'
    - name: Run tests
      run: xcodebuild test -scheme $TEST_SCHEME -testPlan $TEST_SCHEME -destination 'platform=iOS Simulator,OS=$DEVICE_OS,name=$DEVICE_NAME' | xcpretty && exit ${PIPESTATUS[0]}
