# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run tests

on:
  pull_request:
    branches: [ "main", "develop" ]
  issue_comment:
    types: [ created ]
  workflow_dispatch:

env:
  TEST_SCHEME: ReccoUITests
  DEVICE_NAME: iPhone 15
  DEVICE_OS: 17.0.1
  IS_CI: true


jobs:
  test:
    name: Run tests
    runs-on: macos-13
    # Conditional execution based on various criteria
    if: |
      github.base_ref == 'main' || 
      github.base_ref == 'develop' || 
      (github.event_name == 'pull_request' && 
       (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'develop')) || 
      (github.event_name == 'push' && 
       (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'develop')) ||
      (github.event.issue.pull_request && contains(github.event.comment.body, '/test'))

    steps:
      - name: Add workflow started comment to PR
        uses: actions/github-script@v6
        with:
          script: |
            const name = '${{ github.workflow }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const body = `[${name}](${url}) started ⏳`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
      - uses: actions/checkout@v3
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - name: Install SwiftLint
        run: brew update; brew outdated swiftlint || brew upgrade swiftlint
      - name: Run SwiftLint
        run: swiftlint
      - name: Run tests
        run: xcodebuild test -scheme $TEST_SCHEME -testPlan $TEST_SCHEME -destination "platform=iOS Simulator,OS=$DEVICE_OS,name=$DEVICE_NAME" | xcpretty && exit ${PIPESTATUS[0]}
      - name: Add workflow finished comment to PR
        uses: actions/github-script@v6
        with:
          script: |
            const success = '${{ job.status }}' == 'success';
            const name = '${{ github.workflow }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const body = `[${name}](${url}) ${success ? 'succeeded ✅' : 'failed ❌'}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
      - name: Publish finish status
        uses: actions/github-script@v6
        with:
          script: |
            const success = '${{ job.status }}' == 'success';
            const state = success ? 'success' : 'failure'; 

            const response = await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              context: '${{ github.workflow }}',
              state: state
            });
